config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'application'
  root 'microposts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def hello
    # render html: "hello, world!"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
    # gon.user_name = "user_name"
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @microposts = Micropost.all
    @micropost = Micropost.new

    gon.microposts = Micropost.pluck(:content)
    # https://stackoverflow.com/questions/30420968/how-to-use-the-gon-gem-to-show-database-values-rather-than-objects
    # gon.micropost = Micropost.all.as_json
    
    # コンテントだけ取得
    # gon.micropost = Micropost.all.as_json(only: [:content])
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    # respond_to do |format|
      if @micropost.save
        # format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        # format.json { render :show, status: :created, location: @micropost }
      else
        # format.html { render :new }
        # format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvalidCicada</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= include_gon %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<div class="form_elemnt">
  <div class="form-content">
          <%= form_with(model: micropost, local: true) do |form| %>
        <% if micropost.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>
      
            <ul>
              <% micropost.errors.full_messages.each do |message| %>
                <li class="message_list"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="field">
          <!--テキストグラフィカリー-->
              <div class="main">
          			  <div class="text">What is Covid to you?</div>		
           			  <div class="shadow">
          				    <div  class="viewport">
          					      <div class="text">What is Covid to you?</div>
          				    </div>
             			</div>
    		　　　</div>
          <%= form.text_field :content, class: "label_area" %>
        </div>
      
        <div class="actions">
          <%= form.submit 'Send', class: "subimit_btn"%>
        </div>
      <% end %>
  </div>
  
</div>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<!--<div class="start">-->
<!--  <p><%= image_tag "name.png" %></p>-->
<!--</div>-->

<a id="movieButton"><p><%= image_tag "play.png" %></p></a>

<video id ="movie_invalid"  src="https://d23fto7fuil342.cloudfront.net/2021_INVALID_0111.mp4" loop></video>

<!--ここは要らなくなるはず-->
<!--<tbody class="messageToyou">-->
<!--    <% @microposts.each do |micropost| %>-->
<!--      <tr>-->
<!--        <td><%= micropost.content %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
  
<%= render 'form', micropost: @micropost %>

<script>
  console.log('I am who I am, Then we are who we are.')
    $(function() {
  	// setTimeout(function(){
  	// 	$('.start p').fadeIn(1600);
  	// },500); //0.5秒後にロゴをフェードイン!
  	// setTimeout(function(){
  	// 	$('.start').fadeOut(1600);
  	// },1600); //2.5秒後にロゴ含め真っ白背景をフェードアウト！
  	setTimeout(function(){
  		$('#movieButton p').fadeIn(1600);
  	},2500); //0.5秒後にロゴをフェードイン!
  });
  
  $('#movieButton').click(function() {
    setTimeout(function(){
  		$('#movieButton').fadeOut(1600);
  	    },1000); //2.5秒後にロゴ含め真っ白背景をフェードアウト！
       $(function(){
      	setTimeout(function(){
      		$("#movie_invalid")[0].play();
      	},3000);
      });
    	
})

//参考
// pattern1
//https://stackoverflow.com/questions/30420968/how-to-use-the-gon-gem-to-show-database-values-rather-than-objects
// var renderedUsers = JSON.stringify(gon.micropost);
// alert(renderedUsers);
// pattern1 + α
// alert(renderedUsers);
// var obj = JSON.parse(renderedUsers);

//参考
// https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q12183688332
　// テキストのランダム表示
  // var mojiume = new Object();
  // mojiume.list = [
  // "あ", "い", "う", "え", "お",
  // "か", "き", "く", "け", "こ",
  // "さ", "し", "す", "せ", "そ",
  // "た", "ち", "つ", "て", "と"
  // ];
  
  // var mojiume = new Object();
  // var mojiume.list = gon.microposts 
  
  var mojiume = gon.microposts
  mojiume.count = 0;
  mojiume.limit = 50;
  mojiume.set = function(){
      var span = document.createElement("span");
      span.className = "mojiume";
      span.style.left = ( Math.random()*100 )+"%";
      span.style.top =( Math.random()*100 )+"%";
      span.textContent =
      // mojiume.list[ ( mojiume.count++)%mojiume.list.length ];
      mojiume[ ( mojiume.count++)%mojiume.length ];
      document.body.appendChild( span );
      if( document.querySelectorAll(".mojiume").length>=mojiume.limit ){
      clearInterval( mojiume.tmr );
  }
  };
  mojiume.tmr = setInterval( mojiume.set, 10000 );

</script>

<%# テスト %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>